workflow:
  rules:
    - if: '$GITLAB_CI == "false"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

default:
  interruptible: true
  tags:
    - test

stages:
  - build
  - deploy
  - housekeeping

include:
  - local: 'gitlab/build.yml'
  - local: 'gitlab/deploy.yml'
  - local: 'gitlab/housekeeping.yml'
